from app.config import get_settings
settings = get_settings()
print(f"Environment: {settings.APP_ENV}")
print(f"Model: {settings.LITELLM_PRIMARY_CHAT_MODEL}")
print(f"Langchain trace: {settings.LANGCHAIN_TRACING_V2}")
print(f"Rate limit: {settings.RATE_LIMIT}")
print(f"Log level: {settings.LOG_LEVEL}")
print(f"Cache TTL: {settings.CACHE_TTL_SECONDS}")
print(f"Max retries: {settings.MAX_RETRIES}")
print(f"API Key: {settings.LITELLM_CHAT_API_KEY[:10]}...")
print(f"Embedding API Key: {settings.LITELLM_EMBEDDING_API_KEY[:10]}...")
print(f"Langchain API Key: {settings.LANGCHAIN_API_KEY[:10]}...")
print(f"Langchain Project: {settings.LANGCHAIN_PROJECT}")
print(f"is_production: {settings.is_production}")
print("Config loaded successfully")
